export const GET_POSTS = 'GET_POSTS';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_POSTS_FAILURE = 'GET_POSTS_FAILURE';

export const GET_POST_DETAILS = 'GET_POST_DETAILS';
export const GET_POST_DETAILS_SUCCESS = 'GET_POST_DETAILS_SUCCESS';
export const GET_POST_DETAILS_FAILURE = 'GET_POST_DETAILS_FAILURE';

export const VALIDATE_NEW_POST = 'VALIDATE_NEW_POST';
export const CREATE_POST = 'CREATE_POST';
export const RESET_NEW_POST = 'RESET_NEW_POST';